namespace Common.Rest.Shared.Tests;

public class TestEntity : BaseEntity
{
}

[TestClass]
public class BaseEntityTests
{
    [TestMethod]
    public void Id_IsAutoGenerated()
    {
        var entity = new TestEntity();
        Assert.AreNotEqual(Guid.Empty, entity.Id);
    }

    [TestMethod]
    public void CreatedAt_IsSetToUtcNow()
    {
        var before = DateTimeOffset.UtcNow.AddSeconds(-1);
        var entity = new TestEntity();
        var after = DateTimeOffset.UtcNow.AddSeconds(1);

        Assert.IsTrue(entity.CreatedAt >= before);
        Assert.IsTrue(entity.CreatedAt <= after);
    }

    [TestMethod]
    public void DefaultProperties_AreCorrect()
    {
        var entity = new TestEntity();

        Assert.IsNull(entity.PartitionKey);
        Assert.IsNull(entity.CreatedBy);
        Assert.IsNull(entity.UpdatedAt);
        Assert.IsNull(entity.UpdatedBy);
        Assert.IsFalse(entity.IsDeleted);
    }

    [TestMethod]
    public void CanSetAllProperties()
    {
        var now = DateTimeOffset.UtcNow;
        var id = Guid.NewGuid();
        var entity = new TestEntity
        {
            Id = id,
            PartitionKey = "pk-1",
            CreatedAt = now,
            CreatedBy = "user1",
            UpdatedAt = now,
            UpdatedBy = "user2",
            IsDeleted = true
        };

        Assert.AreEqual(id, entity.Id);
        Assert.AreEqual("pk-1", entity.PartitionKey);
        Assert.AreEqual(now, entity.CreatedAt);
        Assert.AreEqual("user1", entity.CreatedBy);
        Assert.AreEqual(now, entity.UpdatedAt);
        Assert.AreEqual("user2", entity.UpdatedBy);
        Assert.IsTrue(entity.IsDeleted);
    }
}

[TestClass]
public class DocumentEntityTests
{
    [TestMethod]
    public void DocumentEntity_CanBeCreated()
    {
        var entity = new DocumentEntity<string>
        {
            DocumentType = "TestDoc",
            JsonData = "some data"
        };

        Assert.AreEqual("TestDoc", entity.DocumentType);
        Assert.AreEqual("some data", entity.JsonData);
        Assert.IsNull(entity.RowVersion);
        Assert.AreNotEqual(Guid.Empty, entity.Id);
    }

    [TestMethod]
    public void DocumentEntity_InheritsBaseEntityProperties()
    {
        var entity = new DocumentEntity<string>
        {
            DocumentType = "String",
            JsonData = "test-data",
            IsDeleted = true
        };

        Assert.IsTrue(entity.IsDeleted);
        Assert.AreEqual("test-data", entity.JsonData);
    }

    [TestMethod]
    public void DocumentEntity_RowVersion_CanBeSet()
    {
        var bytes = new byte[] { 1, 2, 3 };
        var entity = new DocumentEntity<string>
        {
            DocumentType = "Test",
            JsonData = "data",
            RowVersion = bytes
        };

        CollectionAssert.AreEqual(bytes, entity.RowVersion);
    }
}
