// <auto-generated />
using System;
using Common.Rest.Hereditament.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Rest.Hereditament.Infrastructure.Migrations
{
    [DbContext(typeof(HereditamentDocumentDbContext))]
    [Migration("20260421125622_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Rest.Hereditament.Domain.Entities.HereditamentDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateOnly?>("EffectiveFromIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("date")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.Hereditament.organisation')", true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasDefaultValue("{\"uarn\":\"674e7bda-1476-44eb-94fb-7788a5813bbb\",\"name\":\"\",\"effectiveFrom\":\"2026-04-21\",\"status\":\"Draft\"}");

                    b.Property<string>("NameIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.Hereditament.postcode')", true);

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatusIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.Hereditament.streetDescriptor.postTown')", true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("IX_Documents_DocumentType");

                    b.HasIndex("EffectiveFromIndex")
                        .HasDatabaseName("IX_Documents_EffectiveFromIndex");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Documents_IsDeleted");

                    b.HasIndex("NameIndex")
                        .HasDatabaseName("IX_Documents_NameIndex");

                    b.HasIndex("PartitionKey")
                        .HasDatabaseName("IX_Documents_PartitionKey");

                    b.HasIndex("StatusIndex")
                        .HasDatabaseName("IX_Documents_StatusIndex");

                    b.HasIndex("PartitionKey", "DocumentType")
                        .HasDatabaseName("IX_Documents_PartitionKey_DocumentType");

                    b.ToTable("Documents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
