// <auto-generated />
using System;
using Common.Rest.Address.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Rest.Address.Infrastructure.Migrations
{
    [DbContext(typeof(AddressDbContext))]
    [Migration("20260330113304_UpdateAddressModel")]
    partial class UpdateAddressModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Rest.Address.Domain.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfoJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SingleLineAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uprn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Postcode");

                    b.HasIndex("Uprn")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f62e8b2a-8c88-4c8d-8d9e-1f2a3c4d5e6f"),
                            AdditionalInfoJson = "{\"AddressLine1\":\"10 Downing St\",\"AddressLine2\":\"London\",\"AddressLine3\":\"SW1A 2AA\",\"AddressLine4\":\"\",\"AddressLine5\":\"\"}",
                            BuildingName = "Prime Minister's Residence",
                            BuildingNumber = "10",
                            Country = "United Kingdom",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Locality = "Westminster",
                            Postcode = "SW1A 2AA",
                            SingleLineAddress = "10 Downing St, London, SW1A 2AA",
                            Street = "Downing St",
                            Town = "London",
                            Uprn = "100023336491"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-6c7d-8e9f0a1b2c3d"),
                            AdditionalInfoJson = "{\"AddressLine1\":\"1 High St\",\"AddressLine2\":\"Edinburgh\",\"AddressLine3\":\"EH1 1AA\",\"AddressLine4\":\"\",\"AddressLine5\":\"\"}",
                            BuildingName = "Main Building",
                            BuildingNumber = "1",
                            Country = "United Kingdom",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Locality = "City Centre",
                            Postcode = "EH1 1AA",
                            SingleLineAddress = "1 High St, Edinburgh, EH1 1AA",
                            Street = "High St",
                            Town = "Edinburgh",
                            Uprn = "100021234567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
