// <auto-generated />
using System;
using Common.Rest.Address.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Rest.Address.Infrastructure.Migrations
{
    [DbContext(typeof(AddressDocumentDbContext))]
    [Migration("20260411124038_initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Rest.Address.Domain.Entities.AddressDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("DependentLocalityIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.address.streetDescriptor.dependentLocality')", true);

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasDefaultValue("{}");

                    b.Property<string>("LocalityIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.address.streetDescriptor.locality')", true);

                    b.Property<string>("OrganisationIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.address.organisation')", true);

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("PostTownIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.address.streetDescriptor.postTown')", true);

                    b.Property<string>("PostcodeIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.address.postcode')", true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ThoroughfareIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.address.streetDescriptor.streetDescription')", true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("UprnIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("JSON_VALUE([JsonData], '$.uprn')", true);

                    b.HasKey("Id");

                    b.HasIndex("DependentLocalityIndex")
                        .HasDatabaseName("IX_Documents_DependentLocalityIndex");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("IX_Documents_DocumentType");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Documents_IsDeleted");

                    b.HasIndex("LocalityIndex")
                        .HasDatabaseName("IX_Documents_LocalityIndex");

                    b.HasIndex("OrganisationIndex")
                        .HasDatabaseName("IX_Documents_OrganisationIndex");

                    b.HasIndex("PartitionKey")
                        .HasDatabaseName("IX_Documents_PartitionKey");

                    b.HasIndex("PostTownIndex")
                        .HasDatabaseName("IX_Documents_PostTownIndex");

                    b.HasIndex("PostcodeIndex")
                        .HasDatabaseName("IX_Documents_PostcodeIndex");

                    b.HasIndex("ThoroughfareIndex")
                        .HasDatabaseName("IX_Documents_ThoroughfareIndex");

                    b.HasIndex("UprnIndex")
                        .HasDatabaseName("IX_Documents_UprnIndex");

                    b.HasIndex("PartitionKey", "DocumentType")
                        .HasDatabaseName("IX_Documents_PartitionKey_DocumentType");

                    b.ToTable("Documents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
