// <auto-generated />
using System;
using Common.Rest.SurveyData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Rest.SurveyData.Infrastructure.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20260327212814_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Rest.SurveyData.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AssessedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("FloorArea")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FloorAreaUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocalAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PostCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PropertySubType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTimeOffset>("SurveyDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SurveyJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("SurveyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surveyor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Surveys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f62e8b2a-8c88-4c8d-8d9e-1f2a3c4d5e6f"),
                            AssessedValue = 1000000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 27, 21, 28, 12, 168, DateTimeKind.Unspecified).AddTicks(709), new TimeSpan(0, 0, 0, 0, 0)),
                            FloorArea = 1000m,
                            FloorAreaUnit = "sqft",
                            IsDeleted = false,
                            LocalAuthority = "Westminster",
                            Notes = "This is a test survey",
                            PostCode = "SW1A 2AA",
                            PropertyAddress = "10 Downing St, London, SW1A 2AA",
                            PropertySubType = "Detached",
                            PropertyType = "House",
                            ReferenceNumber = "100023336491",
                            Status = "Draft",
                            SurveyDate = new DateTimeOffset(new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SurveyJson = "{\"Uprn\":\"100023336491\",\"SingleLineAddress\":\"10 Downing St, London, SW1A 2AA\",\"BuildingName\":\"Prime Minister\\u0027s Residence\",\"BuildingNumber\":\"10\",\"Street\":\"Downing St\",\"Locality\":\"\",\"Town\":\"London\",\"Postcode\":\"SW1A 2AA\"}",
                            SurveyType = "Valuation",
                            Surveyor = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-6c7d-8e9f0a1b2c3d"),
                            AssessedValue = 1000000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 27, 21, 28, 12, 172, DateTimeKind.Unspecified).AddTicks(1814), new TimeSpan(0, 0, 0, 0, 0)),
                            FloorArea = 1000m,
                            FloorAreaUnit = "sqft",
                            IsDeleted = false,
                            LocalAuthority = "Edinburgh",
                            Notes = "This is a test survey",
                            PostCode = "EH1 1AA",
                            PropertyAddress = "1 High St, Edinburgh, EH1 1AA",
                            PropertySubType = "Detached",
                            PropertyType = "House",
                            ReferenceNumber = "100021234567",
                            Status = "Draft",
                            SurveyDate = new DateTimeOffset(new DateTime(2026, 3, 27, 21, 28, 12, 172, DateTimeKind.Unspecified).AddTicks(1871), new TimeSpan(0, 0, 0, 0, 0)),
                            SurveyJson = "{\"Uprn\":\"100021234567\",\"SingleLineAddress\":\"1 High St, Edinburgh, EH1 1AA\",\"BuildingName\":\"Main Building\",\"BuildingNumber\":\"1\",\"Street\":\"High St\",\"Locality\":\"\",\"Town\":\"Edinburgh\",\"Postcode\":\"EH1 1AA\"}",
                            SurveyType = "Valuation",
                            Surveyor = "John Doe"
                        });
                });

            modelBuilder.Entity("Common.Rest.SurveyData.Domain.Entities.SurveyDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AreaUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RatePerUnit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyDetails", (string)null);
                });

            modelBuilder.Entity("Common.Rest.SurveyData.Domain.Entities.SurveyDetail", b =>
                {
                    b.HasOne("Common.Rest.SurveyData.Domain.Entities.Survey", "Survey")
                        .WithMany("Details")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Common.Rest.SurveyData.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
