@SurveyData.Api_HostAddress = https://localhost:7287

GET {{SurveyData.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SurveyData.Api_HostAddress}}/api/v1/Surveys

###

GET {{SurveyData.Api_HostAddress}}/api/v1/Surveys

###
