global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using FluentAssertions;
global using NSubstitute;
global using SurveyData.Application.DTOs;
global using SurveyData.Application.Interfaces;
global using SurveyData.Domain.Entities;
global using RestApi.Shared.Models;
global using System.Net;
global using System.Net.Http.Json;
